### ISSUE TITLE
Button assignment option: Undo

### ISSUE THREAD

**Issue by danielhigham** [glutanimate/anjoy-public#1]
I'd like to be able to assign a button to ctrl/cmd-z so that I can undo a card rating :)

**Comment by danielhigham** [comment]
Ahhhh, found it in the common tab! 🤦

**Comment by glutanimate** [comment]
Haha, it's a bit hidden away, isn't it? To be honest, was my main concern with making different assignments inherit from each other. If this turns out to be too confusing I'll look into communicating better which actions are inherited on which tab.

Thanks again for the feedback!
